In [8]:
import pandas as pd
import numpy as np

In [13]:
books = pd.read_csv('Books.csv')
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings.csv')

C:\Users\dellu\AppData\Local\Temp\ipykernel_2080\2090938896.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [14]:
print('Books Data')
print(books.isnull().sum())
print('Users Data')
print(users.isnull().sum())
print('Ratings Data')
print(ratings.isnull().sum())

Books Data
ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64
Users Data
User-ID          0
Location         0
Age         110762
dtype: int64
Ratings Data
User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [15]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [16]:
books.head(7)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...

In [17]:
users.sample(7)

        User-ID                            Location   Age
266229   266230           oak view, california, usa  28.0
245890   245891      melbourne, victoria, australia  26.0
227832   227833         pleasanton, california, usa   NaN
244153   244154                  roma, lazio, italy   NaN
68658     68659           singapore, n/a, singapore  21.0
113846   113847                dublin, n/a, ireland  38.0
84601     84602  stirling, scotland, united kingdom  34.0

In [18]:
ratings.sample(7)

         User-ID        ISBN  Book-Rating
756768    182993  0778320170            0
581612    140013  0670033596            0
872876    211400  0061007129            8
1084664   259394  0006485979            3
22258       4556  0425185710            0
806903    196077  0452282152            8
344442     82142  202025462X            0

In [20]:
books.drop_duplicates('Book-Title', inplace=True)

In [21]:
books.duplicated('Book-Title').sum()

np.int64(0)

## **Popularity-based-Recommender**

In [22]:
ratings_with_name = ratings.merge(books, on='ISBN')

In [23]:
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'}, inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241056                                      Ã?Â?lpiraten.            2
241057                     Ã?Â?rger mit Produkt X. Roman.            4
241058                                Ã?Â?sterlich leben.            1
241059                              Ã?Â?stlich der Berge.            3
241060                                  Ã?Â?thique en toc            2

[241061 rows x 2 columns]

In [24]:
avg_rating_df=ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'}, inplace=True)
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241056                                      Ã?Â?lpiraten.    0.000000
241057                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241058                                Ã?Â?sterlich leben.    7.000000
241059                              Ã?Â?stlich der Berge.    2.666667
241060                                  Ã?Â?thique en toc    4.000000

[241061 rows x 2 columns]

In [25]:
popular_df = num_rating_df.merge(avg_rating_df, on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241056,Ã?Â?lpiraten.,2,0.000000
241057,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241058,Ã?Â?sterlich leben.,1,7.000000
241059,Ã?Â?stlich der Berge.,3,2.666667
241060,Ã?Â?thique en toc,2,4.000000

In [26]:
popular_df = popular_df[popular_df['num_ratings'] >=100].sort_values('avg_rating', ascending=False).head(50)
popular_df.shape

(50, 3)

In [27]:
popular_df=popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Year-Of-Publication','Image-URL-M','num_ratings','avg_rating']]

In [28]:
popular_df

,Book-Title,Book-Author,Year-Of-Publication,Image-URL-M,num_ratings,avg_rating
0,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2000,http://images.amazon.com/images/P/0439139597.0...,194,6.541237
1,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,http://images.amazon.com/images/P/0439136350.0...,197,6.467005
2,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,1998,http://images.amazon.com/images/P/0590353403.0...,168,6.363095
3,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,http://images.amazon.com/images/P/043935806X.0...,334,5.571856
4,The Perks of Being a Wallflower,Stephen Chbosky,1999,http://images.amazon.com/images/P/0671027344.0...,103,5.194175
5,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
6,To Kill a Mockingbird,Harper Lee,1988,http://images.amazon.com/images/P/0446310786.0...,389,4.920308
7,The Giver (21st Century Reference),LOIS LOWRY,1994,http://images.amazon.com/images/P/0440219078.0...,178,4.915730
8,Ishmael: An Adventure of the Mind and Spirit,Daniel Quinn,1995,http://images.amazon.com/images/P/0553375407.0...,162,4.907407
9,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,http://images.amazon.com/images/P/059035342X.0...,571,4.900175
10,Interpreter of Maladies,Jhumpa Lahiri,1999,http://images.amazon.com/images/P/039592720X.0...,127,4.874016
11,Anne Frank: The Diary of a Young Girl,ANNE FRANK,1993,http://images.amazon.com/images/P/0553296981.0...,139,4.820144
12,Charlotte's Web (Trophy Newbery),E. B. White,1974,http://images.amazon.com/images/P/0064400557.0...,129,4.782946
13,The Other Boleyn Girl,Philippa Gregory,2002,http://images.amazon.com/images/P/0743227441.0...,156,4.756410
14,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,http://images.amazon.com/images/P/0439064872.0...,351,4.729345
15,Animal Farm,George Orwell,2004,http://images.amazon.com/images/P/0451526341.0...,164,4.695122
16,The Last Juror,John Grisham,2004,http://images.amazon.com/images/P/0385510438.0...,113,4.654867
17,The Da Vinci Code,Dan Brown,2003,http://images.amazon.com/images/P/0385504209.0...,883,4.652322
18,The Catcher in the Rye,J.D. Salinger,1991,http://images.amazon.com/images/P/0316769487.0...,403,4.635236
19,Dragonfly in Amber,DIANA GABALDON,1993,http://images.amazon.com/images/P/0440215625.0...,128,4.632812
20,Stranger in a Strange Land (Remembering Tomorrow),Robert A. Heinlein,1995,http://images.amazon.com/images/P/0441790348.0...,130,4.615385
21,1984,George Orwell,1990,http://images.amazon.com/images/P/0451524934.0...,192,4.614583
22,Dune (Remembering Tomorrow),Frank Herbert,1996,http://images.amazon.com/images/P/0441172717.0...,146,4.609589
23,A Wrinkle In Time,MADELEINE L'ENGLE,1998,http://images.amazon.com/images/P/0440498058.0...,158,4.550633
24,East of Eden (Oprah's Book Club),John Steinbeck,2003,http://images.amazon.com/images/P/0142004235.0...,131,4.549618
25,The Five People You Meet in Heaven,Mitch Albom,2003,http://images.amazon.com/images/P/0786868716.0...,427,4.543326
26,The Stand: Complete and Uncut,Stephen King,1991,http://images.amazon.com/images/P/0451169530.0...,131,4.534351
27,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339703.0...,257,4.505837
28,Coraline,Neil Gaiman,2002,http://images.amazon.com/images/P/0380977788.0...,115,4.504348
29,Life of Pi,Yann Martel,2002,http://images.amazon.com/images/P/0151008116.0...,170,4.500000
30,The World According to Garp,John Irving,1994,http://images.amazon.com/images/P/034536676X.0...,108,4.472222
31,The Lovely Bones: A Novel,Alice Sebold,2002,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
32,Prodigal Summer: A Novel,Barbara Kingsolver,2001,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
33,Naked,David Sedaris,1998,http://images.amazon.com/images/P/0316777730.0...,124,4.419355
34,Where the Red Fern Grows,Wilson Rawls,1984,http://images.amazon.com/images/P/0553274295.0...,112,4.410714
35,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997,http://images.amazon.com/images/P/0385484518.0...,391,4.406650
36,Siddhartha,Hermann Hesse,1981,http://images.amazon.com/images/P/0553208845.0...,101,4.376238
37,Their Eyes Were Watching God: A Novel,Zora Neale Hurston,1990,http://images.amazon.com/images/P/0060916508.0...,100,4.370000
38,The Valley of Horses,JEAN M. AUEL,1984,http://images.amazon.com/images/P/0553250531.0...,130,4.361538
39,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,2002,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
40,Night,Elie Wiesel,1982,http://images.amazon.com/images/P/0553272535.0...,181,4.337017
41,The Red Tent (Bestselling Backlist),Anita Diamant,1998,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
42,Year of Wonders,Geraldine Brooks,2002,http://images.amazon.com/images/P/0142001430.0...,169,4.331361
43,Memoirs of a Geisha Uk,Arthur Golden,0,http://images.amazon.com/images/P/0099771519.0...,163,4.312883
44,The Tao of Pooh,Benjamin Hoff,1983,http://images.amazon.com/images/P/0140067477.0...,189,4.296296
45,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339711.0...,177,4.276836
46,Holes (Yearling Newbery),LOUIS SACHAR,2000,http://images.amazon.com/images/P/0440414806.0...,154,4.272727
47,Neverwhere,Neil Gaiman,1998,http://images.amazon.com/images/P/0380789019.0...,237,4.265823
48,Skipping Christmas,JOHN GRISHAM,2001,http://images.amazon.com/images/P/0385505833.0...,210,4.252381
49,Atlas Shrugged,Ayn Rand,1996,http://images.amazon.com/images/P/0451191145.0...,111,4.252252

In [29]:
popular_df.shape

(50, 6)

## **Collaborative-Filtering-Based-Recommender-System**

In [30]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating']>100
selected_users = x[x].index

In [31]:
selected_users.shape

(1418,)

In [32]:
filtered_rating=ratings_with_name[ratings_with_name['User-ID'].isin(selected_users)]

In [33]:
filtered_rating.shape

(488358, 10)

In [34]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>30
famous_books = y[y].index

In [35]:
famous_books.shape

(1453,)

In [36]:
final_rating=filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [37]:
final_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
990,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
998,277427,0060542128,7,When the Storm Breaks,Heather Lowell,2003,HarperTorch,http://images.amazon.com/images/P/0060542128.0...,http://images.amazon.com/images/P/0060542128.0...,http://images.amazon.com/images/P/0060542128.0...
1001,277427,006092988X,0,A Tree Grows in Brooklyn,Betty Smith,1998,Perennial,http://images.amazon.com/images/P/006092988X.0...,http://images.amazon.com/images/P/006092988X.0...,http://images.amazon.com/images/P/006092988X.0...
1002,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1004,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...
...,...,...,...,...,...,...,...,...,...,...
882907,276680,0449908798,0,Duplicate Keys,Jane Smiley,1993,Ballantine Books,http://images.amazon.com/images/P/0449908798.0...,http://images.amazon.com/images/P/0449908798.0...,http://images.amazon.com/images/P/0449908798.0...
882912,276680,0452283205,7,Falling Angels,Tracy Chevalier,2002,Plume Books,http://images.amazon.com/images/P/0452283205.0...,http://images.amazon.com/images/P/0452283205.0...,http://images.amazon.com/images/P/0452283205.0...
882915,276680,0670030643,0,The Eyre Affair (Alex Awards (Awards)),Jasper Fforde,2002,Viking Books,http://images.amazon.com/images/P/0670030643.0...,http://images.amazon.com/images/P/0670030643.0...,http://images.amazon.com/images/P/0670030643.0...
882922,276680,0679731725,0,The Remains of the Day (Vintage International),Kazuo Ishiguro,1993,Vintage Books USA,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...
882933,276680,0743203631,7,Gap Creek: The Story Of A Marriage,Robert Morgan,2000,Touchstone,http://images.amazon.com/images/P/0743203631.0...,http://images.amazon.com/images/P/0743203631.0...,http://images.amazon.com/images/P/0743203631.0...

In [38]:
pt=final_rating.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating')

In [39]:
pt

User-ID,254,507,882,1424,1435,1733,1903,2033,2110,2276,...,274808,275020,275970,276680,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
16 Lighthouse Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010: Odyssey Two,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204 Rosewood Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
You Belong to Me and Other True Cases (Ann Rule's Crime Files: Vol. 2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
pt.shape

(1453, 1401)

In [41]:
pt.isnull().sum()

User-ID
254       1393
507       1424
882       1418
1424      1439
1435      1424
          ...
277478    1432
277639    1427
278137    1431
278188    1432
278418    1268
Length: 1401, dtype: int64

In [42]:
pt.fillna(0, inplace=True)

User-ID,254,507,882,1424,1435,1733,1903,2033,2110,2276,...,274808,275020,275970,276680,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
204 Rosewood Lane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong to Me and Other True Cases (Ann Rule's Crime Files: Vol. 2),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
pt.shape

(1453, 1401)

In [46]:
from sklearn.metrics.pairwise import cosine_similarity
similarities = cosine_similarity(pt)

In [47]:
similarities.shape

(1453, 1453)

In [48]:
similarities

array([[1.        , 0.        , 0.04329334, ..., 0.11189906, 0.        ,
        0.        ],
       [0.        , 1.        , 0.05436194, ..., 0.07653974, 0.        ,
        0.        ],
       [0.04329334, 0.05436194, 1.        , ..., 0.03311659, 0.1211055 ,
        0.2002365 ],
       ...,
       [0.11189906, 0.07653974, 0.03311659, ..., 1.        , 0.06135151,
        0.03756997],
       [0.        , 0.        , 0.1211055 , ..., 0.06135151, 1.        ,
        0.15832706],
       [0.        , 0.        , 0.2002365 , ..., 0.03756997, 0.15832706,
        1.        ]], shape=(1453, 1453))

In [49]:
# Function for recommendations
def recommend(book_name):
    # fecthing index of user selected movie
    index = np.where(pt.index == book_name)[0][0]
    similar_movies = sorted(list(enumerate(similarities[index])),key=lambda x:x[1],reverse=True)[1:9]

    data = []
    for i in similar_movies:
        item = []
        temp_df = books[books['Book-Title']== pt.index[i[0]]]
        item.extend(list(temp_df['Book-Title'].values))
        item.extend(list(temp_df['Book-Author'].values))
        item.extend(list(temp_df['Image-URL-M'].values))
        item.extend(list(temp_df['Year-Of-Publication'].values))



        data.append(item)

    return data

In [50]:
recommend('2nd Chance')

[['Four Blind Mice',
  'James Patterson',
  'http://images.amazon.com/images/P/0316693006.01.MZZZZZZZ.jpg',
  2002],
 ['Roses Are Red',
  'James Patterson',
  'http://images.amazon.com/images/P/0316693251.01.MZZZZZZZ.jpg',
  2000],
 ['The Lake House',
  'James Patterson',
  'http://images.amazon.com/images/P/0316603287.01.MZZZZZZZ.jpg',
  2003],
 ['Thicker Than Water',
  'Maggie Shayne',
  'http://images.amazon.com/images/P/1551667371.01.MZZZZZZZ.jpg',
  2003],
 ['Cradle and All',
  'James Patterson',
  'http://images.amazon.com/images/P/0316690619.01.MZZZZZZZ.jpg',
  2000],
 ['Almost Paradise',
  'Susan Isaacs',
  'http://images.amazon.com/images/P/0345316770.01.MZZZZZZZ.jpg',
  1990],
 ['The Perfect Summer',
  'Luanne Rice',
  'http://images.amazon.com/images/P/0553584049.01.MZZZZZZZ.jpg',
  2003],
 ["Daddy's Little Girl",
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0743206045.01.MZZZZZZZ.jpg',
  2002]]

In [51]:
import pickle
pickle.dump(popular_df, open('popular_df.pkl', 'wb'))
pickle.dump(pt, open('pt.pkl', 'wb'))
pickle.dump(books, open('books.pkl', 'wb'))
pickle.dump(similarities, open('similarities.pkl', 'wb'))
pickle.dump(recommend, open('recommend.pkl', 'wb'))

In [52]:
popular_df.sample(5)

,Book-Title,Book-Author,Year-Of-Publication,Image-URL-M,num_ratings,avg_rating
14,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,http://images.amazon.com/images/P/0439064872.0...,351,4.729345
23,A Wrinkle In Time,MADELEINE L'ENGLE,1998,http://images.amazon.com/images/P/0440498058.0...,158,4.550633
28,Coraline,Neil Gaiman,2002,http://images.amazon.com/images/P/0380977788.0...,115,4.504348
8,Ishmael: An Adventure of the Mind and Spirit,Daniel Quinn,1995,http://images.amazon.com/images/P/0553375407.0...,162,4.907407
34,Where the Red Fern Grows,Wilson Rawls,1984,http://images.amazon.com/images/P/0553274295.0...,112,4.410714